spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.JdbcClientAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration
      - org.springframework.boot.jooq.autoconfigure.JooqAutoConfiguration
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    org.jooq: DEBUG
